### ISSUE TITLE
Add bugzilla.redhat.com

### ISSUE THREAD

**Issue by gcoxmoz** [jdavis/twofactorauth#6679]
### Site name

Red Hat Bugzilla

### Site URL

bugzilla.redhat.com

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

In #6676 `redhat.com` was added.  However, `bugzilla.redhat.com` has a non-MFA auth distinct from the larger company's SSO, and is incorrectly caught up by the whole domain entry.

**Comment by Carlgo11** [comment]
There's a few issues hindering the addition of `bugzilla.redhat.com`:
1. Bugzilla is a [self-hosted service](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#self-hosted-services). _(See the third eligibility checkbox)_
1. `bugzilla.redhat.com` is unranked on Similarweb which goes against our [guidelines for new entries](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines). _(See the first and second eligibility checkbox)_

I guess you checked the boxes without actually reading the text?

If your intention with this issue is to make a third party app no longer suggest to you to add TOTP to `bugzilla.redhat.com`, I suggest you instead contact that third party as they should be able to exclude the bugzilla subdomain.
