### ISSUE TITLE
Add Wilders Security Forums

### ISSUE THREAD

**Issue by squarePI** [jdavis/twofactorauth#7166]
This site has the following info...

Wilders Security Forums
https://www.wilderssecurity.com
https://www.wilderssecurity.com/account/two-step

Two-Step Verification Methods
Verification Code via App
Email Confirmation
Backup Codes

![Wilders-Security-2FA](https://user-images.githubusercontent.com/99891881/209485006-c55f01bb-dbd6-4574-b762-62b85da4e31a.png)

**Comment by hkamran80** [comment]
This site is not in the top 200,000 sites on [Similarweb](https://www.similarweb.com/), therefore it cannot be added.

**Comment by Carlgo11** [comment]
Hello @squarePI,
Our guidelines on [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) requires new entries to have a global rank of 200,000 or less on [Similarweb](https://www.similarweb.com/website/wilderssecurity.com/#overview).
This requirement is in place because maintaining the lists takes time and a list of all websites on the internet just isn't feasible.

Unfortunately, as the site you want to add is ranked above 200,000 it doesn't meet our guidelines and thus can't be added.

Edit: @hkamran80 is a ninja and managed to post the exact same time as me. :ninja:

**Comment by squarePI** [comment]
I went here>
https://www.similarweb.com/website/wilderssecurity.com/#overview and it
showed that site was #199,893 for the US, so it is close to 200,000. Some
time in the future it could be added.

Am I understanding correctly??

THANKS

**Comment by hkamran80** [comment]
The site uses the global ranking, so if the site gets into the top 200,000 globally in the future, then it can be added.

**Comment by squarePI** [comment]
THANK YOU for being patient with me. :-))

**Comment by hkamran80** [comment]
Any time!
