### ISSUE TITLE
Add [Plisio]

### ISSUE THREAD

**Issue by AdPlisio** [jdavis/twofactorauth#7462]
### Site name

Plisio

### Site URL

https://plisio.net

### Documentation URL

https://plisio.net/faq/how-to-enable-two-factor-authorization

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [X] Email tokens

### Eligibility

- [ ] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
@AdPlisio did you actually check that the site is ranked within the top 200,000 global sites on Similarweb before you clicked that checkbox?

**Comment by AdPlisio** [comment]
@Carlgo11 sorry, I didn’t check the current information - back in February we were in the top 200k

**Comment by Carlgo11** [comment]
Okay.

Unfortunately, as the site you want to add is ranked above 200,000 it doesn't meet our guidelines and thus can't be added at the moment. This requirement is in place because maintaining the lists takes time and a list of all websites on the internet just isn't feasible.  
If the site rises in popularity in the future and becomes ranked below 200,000 on Similarweb, this issue can be reopened.

To prevent any of your future pull requests from being closed, please make sure your contribution adheres to our [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) and [EXCLUSION.md](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) before creating a new pull request. Thank you!
