### ISSUE TITLE
Add Domain-Offensive

### ISSUE THREAD

**Issue by DrPiffl** [jdavis/twofactorauth#7948]
### Site name

Domain-Offensive

### Site URL

https://www.do.de

### Documentation URL

https://www.do.de/wiki/totp/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [X] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

# Categories:
- domains
- hosting
- email

**Comment by Carlgo11** [comment]
Our guidelines on [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) require new entries to have a global rank of 200,000 or less on [Similarweb](https://www.similarweb.com/website/).
This requirement is in place because maintaining the lists takes time, and a list of all websites on the internet isn't feasible.

Unfortunately, as the site you want to add is ranked above 200,000, it doesn't meet our guidelines and thus can't be added. If the site rises in popularity in the future and is ranked below 200,000 on Similarweb, this pull request can be reopened.

To prevent any of your future pull requests from being closed, please make sure your contribution adheres to our [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) and [EXCLUSION.md](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) before creating a new pull request. Thank you!
